plugins {
    id 'java'
    id 'org.springframework.boot' version '4.1.0-RC1'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'org.jetbrains.kotlin.jvm'
    id "org.jetbrains.kotlin.plugin.jpa" version '2.3.10'
    id "org.jetbrains.kotlin.plugin.spring" version '2.3.10'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
description = 'board_test'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
}

ext {
    set('tomcat.version', '11.0.22')
    set('mysql.version', '9.7.0')
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-jdbc'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    testImplementation 'org.springframework.security:spring-security-test'
    compileOnly 'org.projectlombok:lombok'
    runtimeOnly 'com.mysql:mysql-connector-j'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:3.0.3'
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'com.h2database:h2'
    testCompileOnly 'org.projectlombok:lombok'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testAnnotationProcessor 'org.projectlombok:lombok'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
    implementation "org.jetbrains.kotlin:kotlin-stdlib"
}

tasks.named('test') {
    useJUnitPlatform()
}

def frontendDir = "$projectDir/frontend"

task installFrontend(type: Exec) {
    workingDir frontendDir
    inputs.dir frontendDir
    outputs.dir "$frontendDir/node_modules"

    if (System.getProperty('os.name').toLowerCase().contains('windows')) {
        commandLine 'cmd', '/c', 'npm', 'install'
    } else {
        commandLine 'npm', 'install'
    }
}

task buildFrontend(type: Exec) {
    dependsOn installFrontend
    workingDir frontendDir
    inputs.dir frontendDir
    outputs.dir "$frontendDir/dist"

    if (System.getProperty('os.name').toLowerCase().contains('windows')) {
        commandLine 'cmd', '/c', 'npm', 'run', 'build'
    } else {
        commandLine 'npm', 'run', 'build'
    }
}

task copyFrontend(type: Copy) {
    dependsOn buildFrontend
    from "$frontendDir/dist"
    into "$projectDir/src/main/resources/static"
}

processResources.dependsOn copyFrontend

clean.doLast {
    file("$projectDir/src/main/resources/static").deleteDir()
}

